# Generated by Django 5.1.9 on 2026-05-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('literary_fiction', 'Literary Fiction'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('horror', 'Horror'), ('history', 'History'), ('biography', 'Biography'), ('self_help', 'Self Help'), ('philosophy', 'Philosophy'), ('science', 'Science'), ('technology', 'Technology'), ('poetry', 'Poetry'), ('comics', 'Comics & Graphic Novels')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users', to='profiles.genre'),
        ),
    ]
