# Generated by Django 5.1.9 on 2026-05-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_genre_userprofile_interests'),
        ('profiles', '0002_populate_genres'),
    ]

    operations = [
    ]
