# Generated by Django 5.1.9 on 2026-05-15 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_id_alter_message_id'),
        ('exchanges', '0002_alter_exchange_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange', to='chat.conversation'),
        ),
        migrations.CreateModel(
            name='MeetupDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('meetup_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meetup', to='exchanges.exchange')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_meetups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
