# Generated by Django 5.1.9 on 2026-05-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_detail',
            field=models.ImageField(blank=True, null=True, upload_to='books/detail/'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='books/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/original/'),
        ),
    ]
