# Generated by Django 5.1.9 on 2026-05-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_image_detail_book_image_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
